DROP TABLE IF EXISTS
    users,
    items,
    bookings,
    requests,
    comments;

CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    available   BOOLEAN      NOT NULL,
    owner_id    INTEGER      NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    INTEGER                     NOT NULL REFERENCES items (id),
    booker_id  INTEGER                     NOT NULL REFERENCES users (id),
    status     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(200) NOT NULL,
    requestor_id INTEGER      NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(200)                NOT NULL,
    item_id   INTEGER                     NOT NULL REFERENCES items (id),
    author_id INTEGER                     NOT NULL REFERENCES users (id),
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

